### ISSUE TITLE
Package python3-dev needed on Ubuntu 20.04

### ISSUE THREAD

**Issue by mn416** [CTSRD-CHERI/cheribuild#164]
Hi,

I needed `apt install python3-dev` in addition to the Ubuntu dependencies listed in the README in order to build `gdb` when specifying `freestanding-sdk` as the target.  Without this package, I got "no usable python found at /usr/bin/python3" when building `gdb`.  I'm using Ubuntu 20.04.

**Comment by arichardson** [comment]
Should be fixed by https://github.com/CTSRD-CHERI/cheribuild/commit/2276f6461327c0bea78770ca32f41253f8a29a01

Now GDB should autodetect whether python can be used. You will get a GDB without python integration if the -dev package is not installed, but that is not required to get a working GDB (it will just be missing a few features).
