### ISSUE TITLE
Login Credentials - FreeBSD-riscv

### ISSUE THREAD

**Issue by antonionehme** [CTSRD-CHERI/cheribuild#176]
Hi All,

I am trying to build risc-v on an ubuntu VM with cheribuild.py run-riscv64-hybrid -d. My intension is to use QEMU emulation for risc-v. I am however being promped for login credentials during the build process (see screenshot below). Can anyone let me know what these credentials are or where to find them?

![image](https://user-images.githubusercontent.com/11300985/104315950-9fc12500-54d3-11eb-8921-78e3a0b20743.png)

Many thanks,
Antonio

**Comment by rwatson** [comment]
Hi Antonio:

That's the booted CheriBSD hybrid OS instance running on Qemu. You can log in using the username 'root' and no initial password. You can then add a user account (etc) as desired.

For most purposes, we recommend the run-riscv64-purecap rather than -hybrid target, as that gives you a spatially safe and capability-rich userspace. Our pure-capability kernel work is currently being merged to our main branch, but that merge is not yet complete.

Robert

**Comment by antonionehme** [comment]
Many thanks for the explanation! @rwatson
