### ISSUE TITLE
Search path is hardcoded

### ISSUE THREAD

**Issue by ltratt** [CTSRD-CHERI/cheribuild#230]
`cheribuild.py` searches for `clang` in a fixed set of directories (https://github.com/CTSRD-CHERI/cheribuild/blob/master/pycheribuild/processutils.py#L726):

```python
search_path = [Path("/usr/local/bin"), Path("/usr/bin")]
```

Depending on your OS, this can be very surprising: would it make more sense to search through `$PATH` *unless* the user overrides it with `--cc-path` or friends? It would certainly have caused less confusion at our end :)

**Comment by jrtc27** [comment]
No; see https://github.com/CTSRD-CHERI/cheribuild/commit/5d031400094caff8e708032ed7484c0666bebb2e for the rationale.

**Comment by ltratt** [comment]
If so, then wouldn't it be better not to search *any* directories and force the user to specify where `clang` is? The problem we've had is that, currently, it seems to randomly work (or not work!). The problem is that, depending on your OS/distribution, `/usr/bin/` and `/usr/local/bin` are either not particularly privileged, or are not the only privileged directories.

**Comment by jrtc27** [comment]
On all the OSes we support (FreeBSD, macOS, Debian/Ubuntu/Fedora), a system-provided Clang should be in one of those two directories, no? Requiring users to manually specify those standard directories would negate the purpose of cheribuild as a "tries to do the right thing automatically" tool.

What OS are you on, where is your Clang installed to and how/from where was it installed? If there are other common system directories we should be searching we can add those, but all of PATH is not something we'll do, nor is removing the functionality.

**Comment by ltratt** [comment]
I have systems with `clang` in both `/usr/bin/` and `/usr/local/bin`, with the latter coming first in `$PATH`. Anyway, I don't wish to impose my beliefs upon cheribuild, so we'll document this as a "gotcha" at our end, and I'll close the issue.

**Comment by jrtc27** [comment]
Those should still be picked up though, with the latest version used no matter which directory it's in?

**Comment by arichardson** [comment]
If I recall directly I changed the logic from searching all directories in PATH to the hardcoded list to avoid accidentally compiling host binaries with CHERI clang instead of using the system compiler.
I think searching in $PATH instead of the hardcoded list is reasonable as long as we don't include the CHERI and Morello SDK directories. However, I think we should probably still prefer clang binaries found in `/usr/bin` and `/usr/local/bin` before falling back to the rest of PATH since those directories are most likely to contain a compiler that builds working binaries for the current host.

**Comment by ltratt** [comment]
I wonder if we can imagine an alternative scheme that rules out the "accidentally build using CHERI clang" problem while searching `$PATH`?

For example, AFAICS CHERI clang (even if you use it as a cross compiler, which I guess is the issue that https://github.com/CTSRD-CHERI/cheribuild/commit/5d031400094caff8e708032ed7484c0666bebb2e tried to fix) identifies itself as `clang version X.Y.Z (https://github.com/CTSRD-CHERI/llvm-project.git abcdef)`? At which point, perhaps what cheribuild could do is go through `$PATH` in order, but ignore any clang whose version output identifies itself as being built from the CHERI LLVM fork (e.g. with a simple regex over `clang --version`)?

**Comment by jacobbramley** [comment]
I must admit, I didn't realise that it wasn't just searching `PATH` for the host toolchain. My host toolchains live in `/usr/bin` in all my systems, but if (for some reason) I'd built my own, I'd have put it in `$HOME` somewhere (on my `PATH`) and would expect that to be picked over the system version.

I don't think it usually makes sense to put a cross-compiler on your `PATH` with simply-named binaries. Many build systems assume that simply-named tools generate binaries that the host can execute. If you want it there for convenience, many toolchains provide a directory of binaries like `<triple>-c++`, which conveniently stops them from interfering with host binaries. This is not quite true of `output/morello-sdk/bin`, but it would probably be simple to copy some of its symlinks to a `PATH`-safe subdirectory.

I think that would be my preferred, and expected solution: search `PATH` for a host->host toolchain in the usual way, and provide a directory of `<triple>-<tool>` symlinks that users can safely include on their `PATH`.

Failing that, @ltratt's suggestion of using `--version` seems like a promising idea (though note that the Morello version comes from a different URL), though I worry about how reliable that detection mechanism would be. For example, the URLs could change, and I suppose it's possible to build a non-CHERI-aware branch of one of those repositories.

**Comment by jrtc27** [comment]
> I must admit, I didn't realise that it wasn't just searching `PATH` for the host toolchain. My host toolchains live in `/usr/bin` in all my systems, but if (for some reason) I'd built my own, I'd have put it in `$HOME` somewhere (on my `PATH`) and would expect that to be picked over the system version.

Well, that wouldn't be a system compiler, which is what cheribuild searches for.

> I don't think it usually makes sense to put a cross-compiler on your `PATH` with simply-named binaries. Many build systems assume that simply-named tools generate binaries that the host can execute. If you want it there for convenience, many toolchains provide a directory of binaries like `<triple>-c++`, which conveniently stops them from interfering with host binaries. This is not quite true of `output/morello-sdk/bin`, but it would probably be simple to copy some of its symlinks to a `PATH`-safe subdirectory.
>
> I think that would be my preferred, and expected solution: search `PATH` for a host->host toolchain in the usual way, and provide a directory of `<triple>-<tool>` symlinks that users can safely include on their `PATH`.

I disagree. Firstly, "cross-compiler" just does not make sense as a term for Clang, every binary does everything by default. The triple-prefixed binaries are a GCC-ism that only exist for compatibility. The "correct" way to use Clang is `clang --target=foo`, and that is what cheribuild uses, so triple-prefixed symlinks would be of zero use to it, and it should not start using them.

> Failing that, @ltratt's suggestion of using `--version` seems like a promising idea (though note that the Morello version comes from a different URL), though I worry about how reliable that detection mechanism would be. For example, the URLs could change, and I suppose it's possible to build a non-CHERI-aware branch of one of those repositories.

Yes, this is not going to work for various reasons:
1. If you clone from a fork/mirror then it's broken
2. If you get the source from a tarball then it's broken
3. If you use the same repo with multiple remotes, one upstream and one CHERI (and worktrees for each) then it will often fall back to whichever is origin (if the current branch has an upstream then it can determine the right remote, but if your branch has no remote, or your HEAD is detached, it just gets origin's URL)

**Comment by jacobbramley** [comment]
> Well, that wouldn't be a system compiler, which is what cheribuild searches for.

I don't think I fully understand the significance of a "system" compiler, as apposed to any other. It is, in general, possible to replace an OS's default compiler with another, possibly built by a user, and there are several reasons why a user might want to do that. I would expect `PATH` to be a suitable mechanism for selecting such a toolchain.

> > I think that would be my preferred, and expected solution: search `PATH` for a host->host toolchain in the usual way, and provide a directory of `<triple>-<tool>` symlinks that users can safely include on their `PATH`.
> 
> I disagree. Firstly, "cross-compiler" just does not make sense as a term for Clang, every binary does everything by default. The triple-prefixed binaries are a GCC-ism that only exist for compatibility. The "correct" way to use Clang is `clang --target=foo`, and that is what cheribuild uses, so triple-prefixed symlinks would be of zero use to it, and it should not start using them.

That's a good point, about "cross-compiler" terminology, and I agree that cheribuild should continue to use the `--target` mechanism. I think I confused things with my misuse of the terminology, but it's still the case that you have a "host" compiler (probably not CHERI-aware) and another CHERI-aware compiler, built by cheribuild as part of the SDK. Cheribuild knows where the CHERI-aware compiler is, so I don't think that's an issue here (but please correct me if I'm wrong).

If I understand correctly, the searching behaviour (5d03140) is trying to distinguish the two types of toolchain so that it can select the "system" compiler, even if both are on `PATH` with the same names. However, this situation seems unlikely to me: if the CHERI-aware compiler is not suitable for general host ("system") use, then why is it in `PATH`?

On the whole, cheribuild "tries to do the right thing automatically" very succesfully, in my experience, but 5d03140 is surprising to me, and apparently to others too, and has a non-obvious(-to-me) justification.

Here's an idea: if cheribuild needs to keep this searching behaviour, and the user's `PATH` is configured such that it would result in a different toolchain being used, could cheribuild report that as a warning and ask for confirmation? It already has some interactive prompts, e.g. for updating. That way, the behaviour will be maintained, and at least interactive users will be made aware of what's happening.

**Comment by jrtc27** [comment]
> > Well, that wouldn't be a system compiler, which is what cheribuild searches for.
> 
> I don't think I fully understand the significance of a "system" compiler, as apposed to any other. It is, in general, possible to replace an OS's default compiler with another, possibly built by a user, and there are several reasons why a user might want to do that. I would expect `PATH` to be a suitable mechanism for selecting such a toolchain.

By "system compiler" we mean "one provided by your operating system for compiling for your build architecture".

> > > I think that would be my preferred, and expected solution: search `PATH` for a host->host toolchain in the usual way, and provide a directory of `<triple>-<tool>` symlinks that users can safely include on their `PATH`.
> > 
> > 
> > I disagree. Firstly, "cross-compiler" just does not make sense as a term for Clang, every binary does everything by default. The triple-prefixed binaries are a GCC-ism that only exist for compatibility. The "correct" way to use Clang is `clang --target=foo`, and that is what cheribuild uses, so triple-prefixed symlinks would be of zero use to it, and it should not start using them.
> 
> That's a good point, about "cross-compiler" terminology, and I agree that cheribuild should continue to use the `--target` mechanism. I think I confused things with my misuse of the terminology, but it's still the case that you have a "host" compiler (probably not CHERI-aware) and another CHERI-aware compiler, built by cheribuild as part of the SDK. Cheribuild knows where the CHERI-aware compiler is, so I don't think that's an issue here (but please correct me if I'm wrong).
> 
> If I understand correctly, the searching behaviour ([5d03140](https://github.com/CTSRD-CHERI/cheribuild/commit/5d031400094caff8e708032ed7484c0666bebb2e)) is trying to distinguish the two types of toolchain so that it can select the "system" compiler, even if both are on `PATH` with the same names. However, this situation seems unlikely to me: if the CHERI-aware compiler is not suitable for general host ("system") use, then why is it in `PATH`?

Because it can be useful to not have to give the full path every time you want to invoke CHERI Clang or one of the various CHERI-aware binutils (likely llvm-readelf or llvm-objdump). Normally this doesn't cause problems, especially on Linux systems, since build systems tend to default to cc or /usr/bin/cc (and we don't provide a cc symlink), or often gcc on Linux, too. Yes, it is slightly bad practice, but you can often get away with it and it is something people do. As we grow more users, I imagine even more people will do things like that; especially if people start putting _Morello_ compilers in their PATH, which are unable to build the X86 backend, I can foresee all the user support questions from that if cheribuild starts using a Morello Clang as BUILD_CC (or CC for CheriBSD, with XCC being what autotools regards as CC) and can almost guarantee it will happen.

> On the whole, cheribuild "tries to do the right thing automatically" very succesfully, in my experience, but [5d03140](https://github.com/CTSRD-CHERI/cheribuild/commit/5d031400094caff8e708032ed7484c0666bebb2e) is surprising to me, and apparently to others too, and has a non-obvious(-to-me) justification.
> 
> Here's an idea: if cheribuild needs to keep this searching behaviour, and the user's `PATH` is configured such that it would result in a different toolchain being used, could cheribuild report that as a warning and ask for confirmation? It already has some interactive prompts, e.g. for updating. That way, the behaviour will be maintained, and at least interactive users will be made aware of what's happening.

That starts to get awkward with things like usrmerge; PATH will contain /bin, so /bin/clang will exist, for example, and so unless you canonicalise paths you'll end up with a false positive there. On macOS people may have a Homebrew-installed Clang (in /usr/local/bin/clang or /opt/homebrew/bin/clang) but you don't want to use that one even if it exists (although it is keg-only so by default it's kept out of PATH, but people do override that). On FreeBSD you'll have various versioned Clang binaries in /usr/local/bin but want to prefer the system version. There are just too many cases where that doesn't work that it'll just become annoying.

**Comment by arichardson** [comment]
> > Well, that wouldn't be a system compiler, which is what cheribuild searches for.
> 
> I don't think I fully understand the significance of a "system" compiler, as apposed to any other. It is, in general, possible to replace an OS's default compiler with another, possibly built by a user, and there are several reasons why a user might want to do that. I would expect `PATH` to be a suitable mechanism for selecting such a toolchain.
> 
> > > I think that would be my preferred, and expected solution: search `PATH` for a host->host toolchain in the usual way, and provide a directory of `<triple>-<tool>` symlinks that users can safely include on their `PATH`.
> > 
> > 
> > I disagree. Firstly, "cross-compiler" just does not make sense as a term for Clang, every binary does everything by default. The triple-prefixed binaries are a GCC-ism that only exist for compatibility. The "correct" way to use Clang is `clang --target=foo`, and that is what cheribuild uses, so triple-prefixed symlinks would be of zero use to it, and it should not start using them.
> 
> That's a good point, about "cross-compiler" terminology, and I agree that cheribuild should continue to use the `--target` mechanism. I think I confused things with my misuse of the terminology, but it's still the case that you have a "host" compiler (probably not CHERI-aware) and another CHERI-aware compiler, built by cheribuild as part of the SDK. Cheribuild knows where the CHERI-aware compiler is, so I don't think that's an issue here (but please correct me if I'm wrong).
> 
> If I understand correctly, the searching behaviour ([5d03140](https://github.com/CTSRD-CHERI/cheribuild/commit/5d031400094caff8e708032ed7484c0666bebb2e)) is trying to distinguish the two types of toolchain so that it can select the "system" compiler, even if both are on `PATH` with the same names. However, this situation seems unlikely to me: if the CHERI-aware compiler is not suitable for general host ("system") use, then why is it in `PATH`?
> 
> On the whole, cheribuild "tries to do the right thing automatically" very succesfully, in my experience, but [5d03140](https://github.com/CTSRD-CHERI/cheribuild/commit/5d031400094caff8e708032ed7484c0666bebb2e) is surprising to me, and apparently to others too, and has a non-obvious(-to-me) justification.
> 
> Here's an idea: if cheribuild needs to keep this searching behaviour, and the user's `PATH` is configured such that it would result in a different toolchain being used, could cheribuild report that as a warning and ask for confirmation? It already has some interactive prompts, e.g. for updating. That way, the behaviour will be maintained, and at least interactive users will be made aware of what's happening.

I'm not sure if we need to keep this behaviour, it was much more of a problem back when we configured Clang with a default target triple that did not match the host triple. I believe a non-cheribuild Morello LLVM is configured with AArch64 as the default target, so if that ends up in $PATH we suddenly can't build host binaries anymore.
The main goal for cheribuild is to make using CHERI as easy as possible and to make it more difficult for users to shoot themselves in the foot. I recall getting some bug reports a few years ago related to attempting to build with a compiler other than the ones provided by the distribution, so I restricted the search path to /usr/bin and /usr/local/bin.

We are already parsing --version output for those compilers, so we could extend the check to also test for a target triple that matches the host. However, that would require a bit of refactoring since we currently get the default host triple from the default C compiler and I'm not particularly keen on adding more triple logic to cheribuild.

@jrtc27 @jacobbramley @ltratt How do you feel about search $PATH, but ignoring the CHERI+Morello LLVM install dirs (and possibly warning users that adding them to $PATH is not a good idea)? And if you do want to build with a self-built compiler not in PATH you can always use `--cc-path`, etc.

**Comment by ltratt** [comment]
@arichardson Your suggestion seems like a reasonable one to me -- thanks!

**Comment by jrtc27** [comment]
I guess that works. I can think of simple ways to break it, but they're the kinds of thing that people are unlikely to do, and there's only so much we can guard against...
