### ISSUE TITLE
traget morello-llvm specified git revision is different from actual one in the built image

### ISSUE THREAD

**Issue by amrohassaan** [CTSRD-CHERI/cheribuild#255]
In [this](https://git.morello-project.org/morello/llvm-project/-/jobs/55553/raw) CI job for the morello [llvm-project](https://git.morello-project.org/morello/llvm-project/), we build morello-llvm with this revision `+ ./cheribsd/repo/cheribuild.py morello-llvm --morello-llvm/git-revision merge-march2021` which has this sha `4217fea5a3b488adefc82203ee2620ddbc80d8b0` but then qemu boots showing this sha `clang version 11.0.0 (https://git.morello-project.org/morello/llvm-project.git 0e7048bb14a236803e55ffa4dbbb7c64267dd930)` which corresponds to the morello/dev branch which is the default branch for the llvm project and not the one specified above. Is this a bug or did we miss passing an arg somewhere [here](https://git.morello-project.org/morello/morello-ci-pipelines/-/raw/main/.gitlab-ci/build/build-and-test-cheribsd.sh)

**Comment by jrtc27** [comment]
I think this is because of the use of skip-update; currently git-revision isn't honoured by cloning, but is for the subsequent update check, which is still later run when the repo is cloned if you don't skip updating. If you want a hack to fix things today, you should be able to do:
```
./cheribsd/repo/cheribuild.py --skip-build --skip-install morello-llvm
git -C cheribsd/repo/cheribsd/src/morello-llvm-project checkout merge-march2021
./cheribsd/repo/cheribuild.py morello-llvm
```
and things should work. Or just manually clone morello-llvm to cheribsd/repo/cheribsd/src/morello-llvm-project however you like and run `./cheribsd/repo/cheribuild.py morello-llvm`. But this is something we should fix in cheribuild.

**Comment by jrtc27** [comment]
(I'll note though your directory naming scheme is a little odd, given it results in morello-llvm-project under two directories both called cheribsd...)

**Comment by amrohassaan** [comment]
@jrtc27 Thank you. I doubted from the begining that --skip-update in the config would step on our foot for the rest of the script. Thanks for the suggested workaround. I agree on the odd naming which i should probably change.
