### ISSUE TITLE
Failed to invoke compiler in order to build my own code targeting RISC-V purecap on cheriBSD

### ISSUE THREAD

**Issue by ZPedro** [CTSRD-CHERI/cheribuild#380]
This is on Ventura 13.6 (22G120), Xcode 15.0.1, Mac mini M2 (non-pro). I started by successfully running the run-riscv64-purecap, at which point I attempted to try and make my own software run on it.

- I tried running $COMPILER_TRIPLE directly

But that failed to find standard header files.

- I tried providing -isysroot to a direct invocation of $COMPILER_TRIPLE

But that failed at linking, complaining of missing libraries

- I tried passing the "system" (inside ~/cheri/output/sdk/$TRIPLE) library directory with -L and and -Xlinker to a direct invocation of $COMPILER_TRIPLE

But that still failed at linking, this time some "fundamental" object files were reported as missing (e.g. ctrn.o)

- I tried invoking the $COMPILER_TRIPLE along with all the previously mentioned options directly from the "system" (inside ~/cheri/output/sdk/$TRIPLE) library directory

But that still failed at linking, with a shorter list of "fundamental" object files being reported as missing, such as "crti.o"

- I tried installing the cheribsd-sdk-native target

But GDB failed to configure, complaining of missing GMP

- I tried installing GMP in brew, both a native install in /opt/homebrew/ and a Rosetta2-emulated install in /usr/local/

But GDB still failed to configure in the same way

- I tried injecting the location of GMP through $PKG_CONFIG_PATH

But GDB still failed to configure in the same way: it appears the GDB build system does not rely on pkg-config

- I tried starting over and getting back to a revision of the cheribuild repository prior to the switch to GDB 11

But this time the run target failed early in the build, complaining of missing libarchive

- I tried applying https://github.com/CTSRD-CHERI/cheribuild/commit/cb9c7d2b0e3492067256f095bc3bf884478d6c70 directly as a cherry-pick over the last commit prior to the switch to GDB 11

But I got another build failure; at that point, I did not record which, seeing as that did not seem a productive path.

(I did not want to build a SDK without GDB, seeing as I'll likely need to debug the code I wrote. The references to $TRIPLE and the like were actual paths and filenames which I failed to record and can't reference any more now that I've destroyed my ~/cheri environment in a futile attempt to work around the issue).

**Comment by jrtc27** [comment]
All you need is to point --sysroot at the CheriBSD rootfs directory, i.e. ~/cheri/output/rootfs-riscv64-purecap (~/cheri/output/sdk/sysroot-riscv64-purecap should also work, but it's not what cheribuild tends to use) and -B at ~/cheri/output/sdk/bin, plus any other compiler flags needed to set the triple, architecture, ABI, etc. For example, a minimal correct use would be:

```
-target riscv64-unknown-freebsd14 --sysroot=$HOME/cheri/output/rootfs-riscv64-purecap -B$HOME/cheri/output/sdk/bin -march=rv64imafdcxcheri -mabi=l64pc128d -mno-relax
```

~/cheri/output/sdk/utils/cheribsd-riscv64-purecap-clang exists as a convenient wrapper for users to use rather than having to specify those command-line arguments manually (it automatically picks up the set of arguments in ~/cheri/output/sdk/bin/cheribsd-riscv64-purecap.cfg, which you will note is the same as I gave above), though that is intended for users, not machines, to use, i.e. it is not guaranteed to be a stable interface (and hence why it's in utils/ not bin/).

> * I tried installing the cheribsd-sdk-native target
> But GDB failed to configure, complaining of missing GMP

Give cheribsd-sdk-native is not a thing that exists, I don't know if this was you trying to build gdb-native or cross-compile GDB for RISC-V. For the former it should pick up gmp from the system, but I guess there's a chance it's broken. gmp-native does exist as a target you can build for that though. If you're cross-compiling then you will of course need a cross-compiled gmp, for which you can use gmp-<target> to match gdb-<target>.
